apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: dummy-app
          image: nginx
